"""
BOS Code runtime contracts.
"""

SESSION_STATUS_CREATED = "created"
SESSION_STATUS_SPAWNING = "spawning"
SESSION_STATUS_TRUST_REQUIRED = "trust_required"
SESSION_STATUS_READY_FOR_PROMPT = "ready_for_prompt"
SESSION_STATUS_PROMPT_ACCEPTED = "prompt_accepted"
SESSION_STATUS_READY = "ready"
SESSION_STATUS_RUNNING = "running"
SESSION_STATUS_BLOCKED = "blocked"
SESSION_STATUS_COMPLETED = "completed"
SESSION_STATUS_FAILED = "failed"
SESSION_STATUS_CANCELLED = "cancelled"

SESSION_STATUSES = (
    SESSION_STATUS_CREATED,
    SESSION_STATUS_SPAWNING,
    SESSION_STATUS_TRUST_REQUIRED,
    SESSION_STATUS_READY_FOR_PROMPT,
    SESSION_STATUS_PROMPT_ACCEPTED,
    SESSION_STATUS_READY,
    SESSION_STATUS_RUNNING,
    SESSION_STATUS_BLOCKED,
    SESSION_STATUS_COMPLETED,
    SESSION_STATUS_FAILED,
    SESSION_STATUS_CANCELLED,
)

VERIFICATION_STATUS_PENDING = "pending"
VERIFICATION_STATUS_RUNNING = "running"
VERIFICATION_STATUS_PASSED = "passed"
VERIFICATION_STATUS_FAILED = "failed"
VERIFICATION_STATUS_SKIPPED = "skipped"

VERIFICATION_STATUSES = (
    VERIFICATION_STATUS_PENDING,
    VERIFICATION_STATUS_RUNNING,
    VERIFICATION_STATUS_PASSED,
    VERIFICATION_STATUS_FAILED,
    VERIFICATION_STATUS_SKIPPED,
)

TASK_STATUS_CREATED = "created"
TASK_STATUS_RUNNING = "running"
TASK_STATUS_REVIEW_PENDING = "review_pending"
TASK_STATUS_IN_REVIEW = "in_review"
TASK_STATUS_VERIFICATION_PENDING = "verification_pending"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_BLOCKED = "blocked"
TASK_STATUS_FAILED = "failed"

TASK_STATUSES = (
    TASK_STATUS_CREATED,
    TASK_STATUS_RUNNING,
    TASK_STATUS_REVIEW_PENDING,
    TASK_STATUS_IN_REVIEW,
    TASK_STATUS_VERIFICATION_PENDING,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_BLOCKED,
    TASK_STATUS_FAILED,
)

WORKER_STATUS_IDLE = "idle"
WORKER_STATUS_SPAWNING = "spawning"
WORKER_STATUS_TRUST_REQUIRED = "trust_required"
WORKER_STATUS_READY_FOR_PROMPT = "ready_for_prompt"
WORKER_STATUS_PROMPT_ACCEPTED = "prompt_accepted"
WORKER_STATUS_READY = "ready"
WORKER_STATUS_ASSIGNED = "assigned"
WORKER_STATUS_RUNNING = "running"
WORKER_STATUS_WAITING_REVIEW = "waiting_review"
WORKER_STATUS_BLOCKED = "blocked"
WORKER_STATUS_FAILED = "failed"
WORKER_STATUS_COMPLETED = "completed"

WORKER_STATUSES = (
    WORKER_STATUS_IDLE,
    WORKER_STATUS_SPAWNING,
    WORKER_STATUS_TRUST_REQUIRED,
    WORKER_STATUS_READY_FOR_PROMPT,
    WORKER_STATUS_PROMPT_ACCEPTED,
    WORKER_STATUS_READY,
    WORKER_STATUS_ASSIGNED,
    WORKER_STATUS_RUNNING,
    WORKER_STATUS_WAITING_REVIEW,
    WORKER_STATUS_BLOCKED,
    WORKER_STATUS_FAILED,
    WORKER_STATUS_COMPLETED,
)

WORKER_LANE_ARCHITECT = "architect"
WORKER_LANE_EXECUTOR = "executor"
WORKER_LANE_REVIEWER = "reviewer"

WORKER_LANES = (WORKER_LANE_ARCHITECT, WORKER_LANE_EXECUTOR, WORKER_LANE_REVIEWER)

OPERATOR_POSTURE_IDLE = "idle"
OPERATOR_POSTURE_PENDING = "pending"
OPERATOR_POSTURE_PLANNING_REQUIRED = "planning_required"
OPERATOR_POSTURE_EXECUTION_ACTIVE = "execution_active"
OPERATOR_POSTURE_REVIEW_QUEUE = "review_queue"
OPERATOR_POSTURE_REVIEW_ACTIVE = "review_active"
OPERATOR_POSTURE_VERIFICATION_GATE = "verification_gate"
OPERATOR_POSTURE_BLOCKED = "blocked"
OPERATOR_POSTURE_RECOVERY_REQUIRED = "recovery_required"
OPERATOR_POSTURE_DEGRADED = "degraded"
OPERATOR_POSTURE_COMPLETED = "completed"
OPERATOR_POSTURE_MERGE_READY = "merge_ready"

OPERATOR_POSTURES = (
    OPERATOR_POSTURE_IDLE,
    OPERATOR_POSTURE_PENDING,
    OPERATOR_POSTURE_PLANNING_REQUIRED,
    OPERATOR_POSTURE_EXECUTION_ACTIVE,
    OPERATOR_POSTURE_REVIEW_QUEUE,
    OPERATOR_POSTURE_REVIEW_ACTIVE,
    OPERATOR_POSTURE_VERIFICATION_GATE,
    OPERATOR_POSTURE_BLOCKED,
    OPERATOR_POSTURE_RECOVERY_REQUIRED,
    OPERATOR_POSTURE_DEGRADED,
    OPERATOR_POSTURE_COMPLETED,
    OPERATOR_POSTURE_MERGE_READY,
)

ACTION_ARCHITECT_PLAN = "architect_plan"
ACTION_ARCHITECT_ROUTE = "architect_route"
ACTION_REQUEST_REVIEW = "request_review"
ACTION_BEGIN_REVIEW = "begin_review"
ACTION_ACCEPT_REVIEW = "accept_review"
ACTION_REJECT_REVIEW = "reject_review"
ACTION_MARK_REVIEWER_READY = "mark_reviewer_ready"
ACTION_MARK_REVIEWER_BLOCKED = "mark_reviewer_blocked"
ACTION_MARK_EXECUTOR_BLOCKED = "mark_executor_blocked"
ACTION_MARK_EXECUTOR_READY = "mark_executor_ready"
ACTION_MARK_ARCHITECT_READY = "mark_architect_ready"
ACTION_MARK_ARCHITECT_BLOCKED = "mark_architect_blocked"
ACTION_RUN_VERIFICATION = "run_verification"
ACTION_REFRESH_BRANCH = "refresh_branch"
ACTION_RESET_SESSION_READY = "reset_session_ready"
ACTION_INSPECT_DIFF = "inspect_diff"
ACTION_REVIEW_DIFF = "review_diff"
ACTION_PREPARE_MERGE = "prepare_merge"
ACTION_INSPECT_CONTEXT = "inspect_context"

CONTROL_ACTIONS = (
    ACTION_ARCHITECT_PLAN,
    ACTION_ARCHITECT_ROUTE,
    ACTION_REQUEST_REVIEW,
    ACTION_BEGIN_REVIEW,
    ACTION_ACCEPT_REVIEW,
    ACTION_REJECT_REVIEW,
    ACTION_MARK_REVIEWER_READY,
    ACTION_MARK_REVIEWER_BLOCKED,
    ACTION_MARK_EXECUTOR_BLOCKED,
    ACTION_MARK_EXECUTOR_READY,
    ACTION_MARK_ARCHITECT_READY,
    ACTION_MARK_ARCHITECT_BLOCKED,
    ACTION_RUN_VERIFICATION,
    ACTION_REFRESH_BRANCH,
    ACTION_RESET_SESSION_READY,
    ACTION_INSPECT_DIFF,
    ACTION_REVIEW_DIFF,
    ACTION_PREPARE_MERGE,
    ACTION_INSPECT_CONTEXT,
)

ACTION_POLICY_AUTOMATION_SAFE = "automation_safe"
ACTION_POLICY_HUMAN_ONLY = "human_only"
ACTION_POLICY_REVIEW_GATED = "review_gated"

ACTION_POLICIES = (
    ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_POLICY_HUMAN_ONLY,
    ACTION_POLICY_REVIEW_GATED,
)

ACTION_POLICY_BY_ACTION = {
    ACTION_ARCHITECT_PLAN: ACTION_POLICY_HUMAN_ONLY,
    ACTION_ARCHITECT_ROUTE: ACTION_POLICY_HUMAN_ONLY,
    ACTION_REQUEST_REVIEW: ACTION_POLICY_HUMAN_ONLY,
    ACTION_BEGIN_REVIEW: ACTION_POLICY_HUMAN_ONLY,
    ACTION_ACCEPT_REVIEW: ACTION_POLICY_REVIEW_GATED,
    ACTION_REJECT_REVIEW: ACTION_POLICY_REVIEW_GATED,
    ACTION_MARK_REVIEWER_READY: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_MARK_REVIEWER_BLOCKED: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_MARK_EXECUTOR_BLOCKED: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_MARK_EXECUTOR_READY: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_MARK_ARCHITECT_READY: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_MARK_ARCHITECT_BLOCKED: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_RUN_VERIFICATION: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_REFRESH_BRANCH: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_RESET_SESSION_READY: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_INSPECT_DIFF: ACTION_POLICY_AUTOMATION_SAFE,
    ACTION_REVIEW_DIFF: ACTION_POLICY_HUMAN_ONLY,
    ACTION_PREPARE_MERGE: ACTION_POLICY_REVIEW_GATED,
    ACTION_INSPECT_CONTEXT: ACTION_POLICY_AUTOMATION_SAFE,
}


def control_action_policy(action: str) -> str:
    return ACTION_POLICY_BY_ACTION.get(action, ACTION_POLICY_HUMAN_ONLY)

REVIEW_DECISION_ACCEPT = "accept"
REVIEW_DECISION_REJECT = "reject"

REVIEW_DECISIONS = (REVIEW_DECISION_ACCEPT, REVIEW_DECISION_REJECT)

LANE_EVENT_TASK_CREATED = "task.created"
LANE_EVENT_TASK_ROUTED = "task.routed"
LANE_EVENT_STARTED = "lane.started"
LANE_EVENT_PROGRESSED = "lane.progressed"
LANE_EVENT_BLOCKED = "lane.blocked"
LANE_EVENT_COMPLETED = "lane.completed"
LANE_EVENT_REVIEW_REQUESTED = "review.requested"
LANE_EVENT_REVIEW_ACCEPTED = "review.accepted"
LANE_EVENT_REVIEW_REJECTED = "review.rejected"
LANE_EVENT_TASK_COMPLETED = "task.completed"
LANE_EVENT_TASK_FAILED = "task.failed"
LANE_EVENT_MERGE_READINESS_UPDATED = "merge.readiness.updated"

LANE_EVENT_NAMES = (
    LANE_EVENT_TASK_CREATED,
    LANE_EVENT_TASK_ROUTED,
    LANE_EVENT_STARTED,
    LANE_EVENT_PROGRESSED,
    LANE_EVENT_BLOCKED,
    LANE_EVENT_COMPLETED,
    LANE_EVENT_REVIEW_REQUESTED,
    LANE_EVENT_REVIEW_ACCEPTED,
    LANE_EVENT_REVIEW_REJECTED,
    LANE_EVENT_TASK_COMPLETED,
    LANE_EVENT_TASK_FAILED,
    LANE_EVENT_MERGE_READINESS_UPDATED,
)

EVENT_TYPES = (
    "code.session.status",
    "code.turn.delta",
    "code.tool.started",
    "code.tool.finished",
    "code.permission.denied",
    "code.diff.ready",
    "code.verification.started",
    "code.verification.finished",
    "code.session.completed",
    "code.session.failed",
    "code.workspace.lease_changed",
    "code.session.replayed",
)

VERIFICATION_STAGES = ("lint", "typecheck", "unit_test", "build", "smoke_test")

SAFE_TOOL_NAMES = (
    "read_file",
    "glob_search",
    "grep_search",
    "write_file",
    "edit_file",
    "safe_bash",
    "git_ops",
    "danger_bash",
)
