import type { ReactNode } from "react";

import {
  Beaker,
  BookOpen,
  Bot,
  Brain,
  Calculator,
  Cpu,
  FileBadge2,
  Clapperboard,
  FlaskConical,
  GitBranch,
  LayoutDashboard,
  Leaf,
  Orbit,
  Settings,
  ShieldCheck,
  Shuffle,
  TrendingUp,
  Wand2,
} from "lucide-react";

export interface AppNavItem {
  to: string;
  label: string;
  shortLabel: string;
  description: string;
  icon: ReactNode;
  section: string;
  minRole?: string;
  keywords?: string[];
}

export const NAV_ITEMS: AppNavItem[] = [
  {
    to: "/dashboard",
    label: "Executive Overview",
    shortLabel: "Overview",
    description: "System posture, alerts, and release momentum.",
    icon: <LayoutDashboard className="h-5 w-5" />,
    section: "Command",
    keywords: ["overview", "home", "alerts", "executive"],
  },
  {
    to: "/bos",
    label: "BOS Assistant",
    shortLabel: "Assistant",
    description: "Start in the thread, ask what matters, and move into the right product surface.",
    icon: <Bot className="h-5 w-5" />,
    section: "Operations",
    keywords: ["assistant", "chat", "bos", "thread", "copilot"],
  },
  {
    to: "/bos/brain",
    label: "Brain Dashboard",
    shortLabel: "Brain",
    description: "Inspect project brain, decision journal, and evolution heuristics carried by the autonomy runtime.",
    icon: <Brain className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: ["brain", "memory", "evolution", "runtime", "heuristics"],
  },
  {
    to: "/bos/orchestrator",
    label: "BOS Orchestrator",
    shortLabel: "Orchestrator",
    description: "Open the workflow orchestration surface for skills, templates, and multi-step automation.",
    icon: <Wand2 className="h-5 w-5" />,
    section: "Operations",
    keywords: ["orchestrator", "workflow", "template", "automation", "assistant"],
  },
  {
    to: "/bos/console",
    label: "Decision Console",
    shortLabel: "Console",
    description: "Review signal contracts, release posture, portability, and audit packets.",
    icon: <FlaskConical className="h-5 w-5" />,
    section: "Operations",
    keywords: ["decision", "signal", "control", "portability", "audit"],
  },
  {
    to: "/bos/references",
    label: "Reference Atlas",
    shortLabel: "References",
    description: "Inspect BOS-ready species, feedstocks, and manuscript-backed evidence assets.",
    icon: <BookOpen className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: ["references", "species", "feedstocks", "campaigns", "atlas"],
  },
  {
    to: "/bos/signal-lab",
    label: "Signal Lab",
    shortLabel: "Signal Lab",
    description: "Focus one batch at a time across signal freshness, Control-API fit, release posture, and portability.",
    icon: <Orbit className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: ["signal", "lab", "release", "control", "handover", "portability"],
  },
  {
    to: "/bos/simulation-lab",
    label: "3D Lab Twin",
    shortLabel: "3D Lab",
    description: "Open the LabSim Twin Studio with Three.js replay, assay gates, and evidence export.",
    icon: <Cpu className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: [
      "simulation",
      "lab",
      "labsim",
      "3d",
      "three",
      "game",
      "digital twin",
      "sensor",
      "actuator",
      "audit",
      "grub",
      "mealworm",
      "bsf",
      "sludge",
      "heavy metal",
    ],
  },
  {
    to: "/bos/media",
    label: "Media Studio",
    shortLabel: "Media",
    description: "Generate BOS-branded stills and short animations with the internal Remotion runtime.",
    icon: <Clapperboard className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: ["media", "video", "animation", "remotion", "render"],
  },
  {
    to: "/code",
    label: "BOS Code",
    shortLabel: "Code",
    description: "Tenant-isolated coding cockpit with events, diffs, verification, and lease posture.",
    icon: <GitBranch className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: ["code", "workspace", "diff", "verification", "session", "lease"],
  },
  {
    to: "/release",
    label: "Release Center",
    shortLabel: "Release",
    description: "Open the BOS Code trust, verification, and dossier surface.",
    icon: <FileBadge2 className="h-5 w-5" />,
    section: "Operations",
    minRole: "operator",
    keywords: ["release", "trust", "verification", "dossier", "artifacts"],
  },
  {
    to: "/batches",
    label: "Batch Command",
    shortLabel: "Batches",
    description: "Inspect live and historical batch command surfaces.",
    icon: <Beaker className="h-5 w-5" />,
    section: "Operations",
    keywords: ["batch", "command", "queue", "records"],
  },
  {
    to: "/ser",
    label: "SER Compute",
    shortLabel: "SER",
    description: "Run matched-boundary performance calculations.",
    icon: <Calculator className="h-5 w-5" />,
    section: "Analysis",
    keywords: ["ser", "compute", "efficiency", "grade"],
  },
  {
    to: "/simulation",
    label: "Simulation",
    shortLabel: "Simulation",
    description: "Stress-test outcome ranges and sensitivities.",
    icon: <Shuffle className="h-5 w-5" />,
    section: "Analysis",
    keywords: ["simulation", "sensitivity", "monte carlo"],
  },
  {
    to: "/forecast",
    label: "Forecast",
    shortLabel: "Forecast",
    description: "Trend signals, drift, and upcoming release pressure.",
    icon: <TrendingUp className="h-5 w-5" />,
    section: "Analysis",
    keywords: ["forecast", "predict", "trend"],
  },
  {
    to: "/twins",
    label: "Digital Twins",
    shortLabel: "Twins",
    description: "Inspect digital twin state and scenario projections.",
    icon: <Cpu className="h-5 w-5" />,
    section: "Intelligence",
    keywords: ["twin", "model", "digital twin"],
  },
  {
    to: "/sustainability",
    label: "Sustainability",
    shortLabel: "Ledger",
    description: "Review qualified water, energy, and GHG implications.",
    icon: <Leaf className="h-5 w-5" />,
    section: "Intelligence",
    keywords: ["sustainability", "ghg", "water", "energy", "tea"],
  },
  {
    to: "/settings",
    label: "Operator Settings",
    shortLabel: "Settings",
    description: "Identity, access posture, and console presentation controls.",
    icon: <Settings className="h-5 w-5" />,
    section: "System",
    keywords: ["settings", "preferences", "theme", "profile", "access"],
  },
  {
    to: "/admin",
    label: "Control Room",
    shortLabel: "Admin",
    description: "Runtime health, operator governance, and feature-gate posture.",
    icon: <ShieldCheck className="h-5 w-5" />,
    section: "System",
    minRole: "admin",
    keywords: ["admin", "users", "governance", "runtime", "flags"],
  },
];

export function findNavItem(pathname: string) {
  return [...NAV_ITEMS]
    .sort((left, right) => right.to.length - left.to.length)
    .find((item) => pathname.startsWith(item.to));
}
